# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/csmajs/ialve001/final-project-spami-uakun-ialve-ado-bnguy-1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/csmajs/ialve001/final-project-spami-uakun-ialve-ado-bnguy-1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"gmock\" \"gtest\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/csmajs/ialve001/final-project-spami-uakun-ialve-ado-bnguy-1/CMakeFiles /home/csmajs/ialve001/final-project-spami-uakun-ialve-ado-bnguy-1//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/csmajs/ialve001/final-project-spami-uakun-ialve-ado-bnguy-1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Pokemon

# Build rule for target.
Pokemon: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Pokemon
.PHONY : Pokemon

# fast build rule for target.
Pokemon/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pokemon.dir/build.make CMakeFiles/Pokemon.dir/build
.PHONY : Pokemon/fast

#=============================================================================
# Target rules for targets named runTests

# Build rule for target.
runTests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 runTests
.PHONY : runTests

# fast build rule for target.
runTests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/build
.PHONY : runTests/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googlemock/CMakeFiles/gmock.dir/build.make googletest/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googlemock/CMakeFiles/gmock_main.dir/build.make googletest/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googletest/CMakeFiles/gtest.dir/build.make googletest/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googletest/CMakeFiles/gtest_main.dir/build.make googletest/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

lib/Display.o: lib/Display.cpp.o
.PHONY : lib/Display.o

# target to build an object file
lib/Display.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pokemon.dir/build.make CMakeFiles/Pokemon.dir/lib/Display.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/lib/Display.cpp.o
.PHONY : lib/Display.cpp.o

lib/Display.i: lib/Display.cpp.i
.PHONY : lib/Display.i

# target to preprocess a source file
lib/Display.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pokemon.dir/build.make CMakeFiles/Pokemon.dir/lib/Display.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/lib/Display.cpp.i
.PHONY : lib/Display.cpp.i

lib/Display.s: lib/Display.cpp.s
.PHONY : lib/Display.s

# target to generate assembly for a file
lib/Display.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pokemon.dir/build.make CMakeFiles/Pokemon.dir/lib/Display.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/lib/Display.cpp.s
.PHONY : lib/Display.cpp.s

lib/Game.o: lib/Game.cpp.o
.PHONY : lib/Game.o

# target to build an object file
lib/Game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pokemon.dir/build.make CMakeFiles/Pokemon.dir/lib/Game.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/lib/Game.cpp.o
.PHONY : lib/Game.cpp.o

lib/Game.i: lib/Game.cpp.i
.PHONY : lib/Game.i

# target to preprocess a source file
lib/Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pokemon.dir/build.make CMakeFiles/Pokemon.dir/lib/Game.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/lib/Game.cpp.i
.PHONY : lib/Game.cpp.i

lib/Game.s: lib/Game.cpp.s
.PHONY : lib/Game.s

# target to generate assembly for a file
lib/Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pokemon.dir/build.make CMakeFiles/Pokemon.dir/lib/Game.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/lib/Game.cpp.s
.PHONY : lib/Game.cpp.s

lib/Item.o: lib/Item.cpp.o
.PHONY : lib/Item.o

# target to build an object file
lib/Item.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pokemon.dir/build.make CMakeFiles/Pokemon.dir/lib/Item.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/lib/Item.cpp.o
.PHONY : lib/Item.cpp.o

lib/Item.i: lib/Item.cpp.i
.PHONY : lib/Item.i

# target to preprocess a source file
lib/Item.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pokemon.dir/build.make CMakeFiles/Pokemon.dir/lib/Item.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/lib/Item.cpp.i
.PHONY : lib/Item.cpp.i

lib/Item.s: lib/Item.cpp.s
.PHONY : lib/Item.s

# target to generate assembly for a file
lib/Item.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pokemon.dir/build.make CMakeFiles/Pokemon.dir/lib/Item.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/lib/Item.cpp.s
.PHONY : lib/Item.cpp.s

lib/Player.o: lib/Player.cpp.o
.PHONY : lib/Player.o

# target to build an object file
lib/Player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pokemon.dir/build.make CMakeFiles/Pokemon.dir/lib/Player.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/lib/Player.cpp.o
.PHONY : lib/Player.cpp.o

lib/Player.i: lib/Player.cpp.i
.PHONY : lib/Player.i

# target to preprocess a source file
lib/Player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pokemon.dir/build.make CMakeFiles/Pokemon.dir/lib/Player.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/lib/Player.cpp.i
.PHONY : lib/Player.cpp.i

lib/Player.s: lib/Player.cpp.s
.PHONY : lib/Player.s

# target to generate assembly for a file
lib/Player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pokemon.dir/build.make CMakeFiles/Pokemon.dir/lib/Player.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/lib/Player.cpp.s
.PHONY : lib/Player.cpp.s

lib/Pokemon.o: lib/Pokemon.cpp.o
.PHONY : lib/Pokemon.o

# target to build an object file
lib/Pokemon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pokemon.dir/build.make CMakeFiles/Pokemon.dir/lib/Pokemon.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/lib/Pokemon.cpp.o
.PHONY : lib/Pokemon.cpp.o

lib/Pokemon.i: lib/Pokemon.cpp.i
.PHONY : lib/Pokemon.i

# target to preprocess a source file
lib/Pokemon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pokemon.dir/build.make CMakeFiles/Pokemon.dir/lib/Pokemon.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/lib/Pokemon.cpp.i
.PHONY : lib/Pokemon.cpp.i

lib/Pokemon.s: lib/Pokemon.cpp.s
.PHONY : lib/Pokemon.s

# target to generate assembly for a file
lib/Pokemon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pokemon.dir/build.make CMakeFiles/Pokemon.dir/lib/Pokemon.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/lib/Pokemon.cpp.s
.PHONY : lib/Pokemon.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pokemon.dir/build.make CMakeFiles/Pokemon.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pokemon.dir/build.make CMakeFiles/Pokemon.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pokemon.dir/build.make CMakeFiles/Pokemon.dir/main.cpp.s
.PHONY : main.cpp.s

tests/GameTest.o: tests/GameTest.cpp.o
.PHONY : tests/GameTest.o

# target to build an object file
tests/GameTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/tests/GameTest.cpp.o
.PHONY : tests/GameTest.cpp.o

tests/GameTest.i: tests/GameTest.cpp.i
.PHONY : tests/GameTest.i

# target to preprocess a source file
tests/GameTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/tests/GameTest.cpp.i
.PHONY : tests/GameTest.cpp.i

tests/GameTest.s: tests/GameTest.cpp.s
.PHONY : tests/GameTest.s

# target to generate assembly for a file
tests/GameTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/tests/GameTest.cpp.s
.PHONY : tests/GameTest.cpp.s

tests/PlayerTest.o: tests/PlayerTest.cpp.o
.PHONY : tests/PlayerTest.o

# target to build an object file
tests/PlayerTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/tests/PlayerTest.cpp.o
.PHONY : tests/PlayerTest.cpp.o

tests/PlayerTest.i: tests/PlayerTest.cpp.i
.PHONY : tests/PlayerTest.i

# target to preprocess a source file
tests/PlayerTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/tests/PlayerTest.cpp.i
.PHONY : tests/PlayerTest.cpp.i

tests/PlayerTest.s: tests/PlayerTest.cpp.s
.PHONY : tests/PlayerTest.s

# target to generate assembly for a file
tests/PlayerTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/tests/PlayerTest.cpp.s
.PHONY : tests/PlayerTest.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... Pokemon"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... runTests"
	@echo "... lib/Display.o"
	@echo "... lib/Display.i"
	@echo "... lib/Display.s"
	@echo "... lib/Game.o"
	@echo "... lib/Game.i"
	@echo "... lib/Game.s"
	@echo "... lib/Item.o"
	@echo "... lib/Item.i"
	@echo "... lib/Item.s"
	@echo "... lib/Player.o"
	@echo "... lib/Player.i"
	@echo "... lib/Player.s"
	@echo "... lib/Pokemon.o"
	@echo "... lib/Pokemon.i"
	@echo "... lib/Pokemon.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... tests/GameTest.o"
	@echo "... tests/GameTest.i"
	@echo "... tests/GameTest.s"
	@echo "... tests/PlayerTest.o"
	@echo "... tests/PlayerTest.i"
	@echo "... tests/PlayerTest.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

